apiVersion: 1

datasources:
  - name: Timescale
    uid: timescale
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: $__env{POSTGRES_DB}
    user: $__env{POSTGRES_USER}
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
